
import streamlit as st
import pandas as pd
import joblib
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from io import BytesIO
import shap
import numpy as np
import pdfplumber
from docx import Document
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import re

# PAGE CONFIG
st.set_page_config(page_title="Fake Job Detector", page_icon="🔍", layout="wide")


# For Generating PDF
def generate_pdf_report(job_title, prediction, confidence,
                        risk_score, reasons, shap_explanations):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>FAKE JOB ANALYSIS REPORT</b>", styles['Title']))
    story.append(Paragraph("<br/><br/>", styles['Normal']))

    story.append(Paragraph(f"<b>Job Title:</b> {job_title}", styles['Normal']))
    story.append(Paragraph(f"<b>Prediction:</b> {prediction}", styles['Normal']))
    story.append(Paragraph(f"<b>Confidence:</b> {confidence:.2%}", styles['Normal']))
    story.append(Paragraph(f"<b>Risk Score:</b> {risk_score}/100", styles['Normal']))

    story.append(Paragraph("<br/><b>Risk Factors</b>", styles['Heading2']))

    if reasons:
        for reason in reasons:
            story.append(Paragraph(f"• {reason}", styles['Normal']))
    else:
        story.append(Paragraph("No suspicious indicators found.", styles['Normal']))
    
    
    # AI Model Explanation (SHAP)
    story.append(Paragraph("<br/><b>AI Model Explanation (SHAP)</b>", styles['Heading2']))
    
    if shap_explanations:
        for explanation in shap_explanations:
            story.append(Paragraph(f"• {explanation}", styles['Normal']))
    else:
        story.append(Paragraph("No SHAP explanation available.", styles['Normal']))
    
    
    # Recommendation
    story.append(Paragraph("<br/><b>Recommendation</b>", styles['Heading2']))


    if risk_score >= 70:
        recommendation = "High Risk. Verify the company before applying."
    elif risk_score >= 40:
        recommendation = "Medium Risk. Review the job carefully."
    else:
        recommendation = "Low Risk. Job appears relatively safe."

    story.append(Paragraph(recommendation, styles['Normal']))

    story.append(Paragraph("<br/><br/>Generated by AI Fake Job Detection System",
                           styles['Italic']))

    doc.build(story)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf


# Resume opening function for PDF
def extract_pdf_text(file):

    text = ""

    with pdfplumber.open(file) as pdf:

        for page in pdf.pages:

            page_text = page.extract_text()

            if page_text:

                text += page_text

    return text

# Resume opening function for DOCX
def extract_docx_text(file):

    doc = Document(file)

    text = "\n".join(
        para.text for para in doc.paragraphs)

    return text

skills = ["python",
    "sql",
    "excel",
    "power bi",
    "tableau",
    "machine learning",
    "deep learning",
    "nlp",
    "tensorflow",
    "pandas",
    "numpy",
    "scikit-learn",
    "statistics",
    "communication",
    "git",
    "aws"]


# RISK ANALYZER FUNCTION
def analyze_job_risk(text, company_profile, salary, has_logo):
    reasons = []
    risk_score = 0

    text = str(text).lower()

    urgent_words = [
        "urgent", "immediately", "asap",
        "limited", "hiring now", "quickly"
    ]

    money_words = [
        "earn", "income", "bonus",
        "salary", "weekly", "daily"
    ]

    fee_words = [
        "fee", "registration",
        "deposit", "payment", "processing fee"
    ]

    if any(word in text for word in urgent_words):
        reasons.append("⚠️ Urgency keywords detected")
        risk_score += 20

    if any(word in text for word in money_words):
        reasons.append("💰 Unrealistic earning related words found")
        risk_score += 15

    if any(word in text for word in fee_words):
        reasons.append("💳 Registration / Processing fee detected")
        risk_score += 25

    if len(str(company_profile).strip()) < 30:
        reasons.append("🏢 Company profile is too short or missing")
        risk_score += 20

    if has_logo == 0:
        reasons.append("🖼 Company logo not available")
        risk_score += 10

    if salary == "":
        reasons.append("💵 Salary information missing")
        risk_score += 10

    risk_score = min(risk_score, 100)

    return reasons, risk_score

    
# LOAD MODEL
@st.cache_resource
def load_model():
    return joblib.load("fake_job_detector.pkl")

model = load_model()

# Load SHAP components
preprocessor = joblib.load("preprocessor.pkl")
classifier = joblib.load("xgb_model.pkl")
feature_names = joblib.load("feature_names.pkl")

# SHAP Explainer
explainer = shap.TreeExplainer(classifier)

# SESSION STATE
if "history" not in st.session_state:
    st.session_state.history = []


# SIDEBAR
st.sidebar.title("📌 Navigation")
page = st.sidebar.radio("Go To", ["Prediction", "About Project"])
st.sidebar.markdown("---")
st.sidebar.subheader("📈 Model Performance")
st.sidebar.metric("Accuracy", "98.77%")
st.sidebar.metric("Precision", "88.62%")
st.sidebar.metric("Recall", "85.55%")
st.sidebar.metric("F1 Score", "87.06%")
st.sidebar.metric("ROC-AUC", "99.17%")


# ABOUT PAGE
if page == "About Project":

    st.title("📊 Fake Job Posting Detection")

    st.markdown("---")

    st.write("""
### Project Overview

This Machine Learning application detects whether a job posting is Genuine or Fraudulent.

### Features

✅ NLP Based Text Processing

✅ TF-IDF Vectorization

✅ One-Hot Encoding

✅ XGBoost Classification

✅ Real-Time Prediction

### Model Performance

- Accuracy: 98.77%
- Precision: 88.62%
- Recall: 85.55%
- F1 Score: 87.06%
- ROC-AUC: 99.17%

### Tech Stack

- Python
- Pandas
- Scikit-Learn
- XGBoost
- Streamlit
""")


# PREDICTION PAGE
if page == "Prediction":

    st.title("🔍 Fake Job Detection System")

    st.markdown(
        "Detect whether a job posting is **Genuine** or **Fraudulent**.")

    st.markdown("---")

    col1, col2 = st.columns(2)

    with col1:

        title = st.text_input("Job Title")

        company_profile = st.text_area("Company Profile")

        description = st.text_area("Job Description")

        requirements = st.text_area("Requirements")

        benefits = st.text_area("Benefits")

    with col2:

        employment_type = st.selectbox(
            "Employment Type",
            [
                "Full-time",
                "Part-time",
                "Contract",
                "Temporary",
                "Unknown"
            ]
        )

        required_experience = st.selectbox(
            "Required Experience",
            [
                "Internship",
                "Entry level",
                "Associate",
                "Mid-Senior level",
                "Executive",
                "Unknown"
            ]
        )

        required_education = st.selectbox(
            "Required Education",
            [
                "High School",
                "Bachelor's Degree",
                "Master's Degree",
                "Doctorate",
                "Unknown"
            ]
        )

        industry = st.text_input("Industry")

        function = st.text_input("Function")

        salary_range = st.text_input("Salary Range")

        telecommuting = st.selectbox("Remote Job", [0, 1])

        has_company_logo = st.selectbox("Company Logo Available",[0, 1])

        has_questions = st.selectbox(
            "Screening Questions",[0, 1])

    st.markdown("### 📄 Upload Resume")

    resume_file = st.file_uploader(
        "Upload Resume",
        type=["pdf", "docx"])
    
    
    st.markdown("---")

    if st.button("🚀 Predict",use_container_width=True):

        # Input Validation

        if title.strip() == "" or description.strip() == "":
            st.warning("Please enter Job Title and Job Description.")
            st.stop()

        try:
            text = (
                str(title) + " " +
                str(company_profile) + " " +
                str(description) + " " +
                str(requirements) + " " +
                str(benefits)
            )


            input_df = pd.DataFrame({
                "text": [text],
                "employment_type": [employment_type],
                "required_experience": [required_experience],
                "required_education": [required_education],
                "industry": [industry],
                "function": [function],
                "salary_range": [salary_range],
                "telecommuting": [telecommuting],
                "has_company_logo": [has_company_logo],
                "has_questions": [has_questions]
            })

            prediction = model.predict(input_df)[0]
            resume_text = ""

            if resume_file is not None:
            
                if resume_file.name.endswith(".pdf"):
            
                    resume_text = extract_pdf_text(resume_file)
            
                elif resume_file.name.endswith(".docx"):
            
                    resume_text = extract_docx_text(resume_file)
            probability = model.predict_proba(input_df)

            if resume_text != "":

                job_text = text
            
                vectorizer = TfidfVectorizer()
            
                vectors = vectorizer.fit_transform([resume_text, job_text])
            
                similarity = cosine_similarity(vectors[0],vectors[1])[0][0]
            
                match_score = similarity * 100
            
                st.markdown("---")
            
                st.subheader("📄 Resume Match Score")
            
                st.metric("Match Percentage",f"{match_score:.2f}%")
            
                st.progress(match_score / 100)
            

                resume_lower = resume_text.lower()
    
                job_lower = text.lower()
                
                resume_skills = []
                
                job_skills = []
                
                for skill in skills:
                
                    if skill in resume_lower:
                
                        resume_skills.append(skill)
                
                    if skill in job_lower:
                
                        job_skills.append(skill)
            
                missing = list(set(job_skills) - set(resume_skills))
                
                matched = list(set(job_skills) & set(resume_skills))
    
                st.markdown("---")
                st.subheader("📄 Resume Skill Analysis")
            
                col1, col2 = st.columns(2)
                
                with col1:
                
                    st.success("✅ Skills Found")
                
                    for skill in matched:
                
                        st.write("✔", skill.title())
                
                with col2:
                
                    st.error("❌ Missing Skills")
                
                    for skill in missing:
                
                        st.write("✖", skill.title())

            else:
                st.info("📄 Upload a resume to see Resume Match Score and Skill Analysis.")
            
            # SHAP EXPLANATION
            
            # Transform input using saved preprocessor
            input_transformed = preprocessor.transform(input_df)
            
            # Generate SHAP values
            shap_values = explainer.shap_values(input_transformed)
            
            # Create DataFrame
            shap_df = pd.DataFrame({"Feature": feature_names,
                "SHAP": shap_values[0]})
            
            # Importance
            shap_df["Importance"] = np.abs(shap_df["SHAP"])
            
            # Top Positive Features
            top_positive = (shap_df.sort_values("SHAP", ascending=False).head(5))
            
            # Top Negative Features
            top_negative = (shap_df.sort_values("SHAP").head(5))
            
            
            # AI Risk Analyzer
            reasons, risk_score = analyze_job_risk(
                            text=text,
                            company_profile=company_profile,
                            salary=salary_range,
                            has_logo=has_company_logo)

            fake_prob = probability[0][1]
            real_prob = probability[0][0]

            confidence = max(fake_prob,real_prob)
            st.markdown("## Prediction Result")

            if prediction == 1:

                st.error("⚠️ Fake Job Detected")

            else:

                st.success("✅ Genuine Job Posting")

            st.markdown("---")
            st.subheader("🛡️ AI Risk Analysis")
            
            # Risk Score
            st.metric("Fraud Risk Score",f"{risk_score}%")
            
            # Progress Bar
            st.progress(risk_score / 100)
            
            # Reasons
            if reasons:
                st.markdown("### 🚩 Risk Factors Found")
                for reason in reasons:
                    st.warning(reason)
            else:
                st.success("✅ No suspicious indicators detected.")
            
            # Recommendation
            st.markdown("### 📌 Recommendation")
            
            if risk_score >= 70:
                st.error("❌ High Risk: Verify the company before applying.")
            elif risk_score >= 40:
                st.warning("⚠️ Medium Risk: Review the job posting carefully.")
            else:
                st.success("✅ Low Risk: The job appears relatively safe.")

                

            st.metric("Confidence Score",f"{confidence:.2%}")
            st.progress(float(confidence))
            st.markdown("---")
            st.subheader("🧠 AI Model Explanation (SHAP)")
            
            # Remove meaningless tokens
            ignore_words = [
                "000","00","10","100","500","1000",
                "right","left","new","one","two",
                "job","work","team","company"
            ]
            
            # Keep only meaningful features
            top_display = top_positive[
                ~top_positive["Feature"].str.lower().str.contains(
                    "|".join(ignore_words),
                    regex=True)].head(5)
            
            if len(top_display) > 0:
                shap_explanations = []
                for _, row in top_display.iterrows():
            
                    feature = str(row["Feature"]).lower()

                    # Human readable explanation
                    if "earn" in feature or "income" in feature or "salary" in feature:
                        message = "💰 Earnings or salary-related words increased fraud risk."
                    
                    elif "logo" in feature:
                        message = "🏢 Company logo strongly influenced the prediction."
                    
                    elif "telecommuting" in feature:
                        message = "🌍 Remote job information influenced the prediction."
                    
                    elif "experience" in feature:
                        message = "👨‍💼 Experience requirement affected the prediction."
                    
                    elif "education" in feature:
                        message = "🎓 Education requirement contributed to the prediction."
                    
                    elif "registration" in feature or "fee" in feature:
                        message = "💳 Registration or fee-related words increased fraud risk."
                    
                    elif "urgent" in feature:
                        message = "⚠️ Urgency-related language increased fraud risk."
                    
                    elif "company_profile" in feature:
                        message = "🏢 Company profile information influenced the prediction."
                    
                    else:
                        message = f"📌 Keyword '{feature}' influenced the model prediction."

                        
                    shap_explanations.append(message)
                    st.info(message)
            
            else:
                shap_explanations = ["No significant feature explanation available."]
                st.info("No significant feature explanation available.")
            st.caption("Higher confidence means the model is more certain about its prediction.")
            
            st.markdown("---")
            st.subheader("📊 Prediction Probabilities")

            prob_df = pd.DataFrame({
                "Class": ["Genuine","Fake"],
                "Probability": [real_prob,fake_prob]
            })

            st.bar_chart(prob_df.set_index("Class"))
            st.write(f"✅ Genuine Job Probability: {real_prob:.2%}")
            st.write(f"⚠️ Fake Job Probability: {fake_prob:.2%}")

            # For Dowload PDF
            pdf = generate_pdf_report(job_title=title,
                prediction="Fake Job" if prediction == 1 else "Genuine Job",
                confidence=confidence,
                risk_score=risk_score,
                reasons=reasons,
                shap_explanations=shap_explanations)
        
            st.download_button(
            label="📄 Download Analysis Report",
            data=pdf,
            file_name="Fake_Job_Analysis_Report.pdf",
            mime="application/pdf")

            # History
            st.session_state.history.append({

                "Job Title": title,

                "Prediction":
                "Fake"
                if prediction == 1
                else "Genuine",

                "Confidence (%)":
                round(
                    confidence * 100,
                    2
                )
            })

            if len(st.session_state.history) > 0:

                st.markdown("---")
                st.subheader("📜 Prediction History")
                history_df = pd.DataFrame(st.session_state.history)
                st.dataframe(history_df,use_container_width=True)

        except Exception as e:

            st.error(f"Error occurred: {e}")
